### ISSUE TITLE
ContextSeedData not working

### ISSUE THREAD

**Issue by arianshahalami** [HamidMosalla/FreelancerBlog#2] opened 2019-05-29 10:21 UTC
Hi there, there is a problem with FreelanceBlogContextSeedData.cs. When I launch the code, I get this error in that class :
System.ObjectDisposedException: 'Cannot access a disposed object. A common cause of this error is disposing a context that was resolved from dependency injection and then later trying to use the same context instance elsewhere in your application. This may occur if you are calling Dispose() on the context, or wrapping the context in a using statement. If you are using dependency injection, you should let the dependency injection container take care of disposing context instances.
Object name: 'FreelancerBlogContext'.'

HERE IS A RELATED IMAGE
![Untitled](https://user-images.githubusercontent.com/19666867/58549624-29e64800-8221-11e9-87cc-bfbbc91b52ce.png)

**Comment by blagojcej** [comment] 2019-10-30 11:42
You should add .Wait() to SeedAdminUser method in Startup->Configure and change return type of SeedAdminUser method from void to Task.
`seeder.SeedAdminUser().Wait();`

**Comment by HamidMosalla** [comment] 2020-08-11 12:54
The issue is fixed now.

**Closed as completed by HamidMosalla** 2020-08-11 12:54 UTC
